import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import Layout from '../../components/Layout'
import { Badge, ChainViewer } from '../../components/common'
import { useApp } from '../../context/AppContext'

export default function BuyerOrders() {
  const { user, db } = useApp()
  const navigate = useNavigate()
  const [orders, setOrders] = useState([])
  const [selected, setSelected] = useState(null)

  useEffect(() => {
    const o = db.where('orders', o => o.buyerId === user.id)
      .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
    setOrders(o)
  }, [user.id])

  const enrich = o => ({
    ...o,
    batch: db.getById('batches', o.batchId),
    farmer: db.getById('users', o.sellerId),
    cert: db.where('certificates', c => c.orderId === o.id)[0],
    txns: db.where('transactions', t => t.batchId === o.batchId),
  })

  function printCert(cert, order, batch, farmer) {
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>Export Certificate — ${cert.id}</title>
      <style>
        body{font-family:Arial;padding:40px;max-width:600px;margin:0 auto;}
        .header{text-align:center;border-bottom:3px solid #1F4E79;padding-bottom:20px;margin-bottom:24px;}
        .logo{font-size:24px;font-weight:800;color:#1F4E79;margin-bottom:4px;}
        .subtitle{color:#666;font-size:13px;}
        h2{color:#1F4E79;font-size:18px;margin-bottom:16px;}
        table{width:100%;border-collapse:collapse;margin-bottom:20px;}
        td{padding:8px 10px;border:1px solid #e2e8f0;font-size:13px;}
        td:first-child{background:#f8faff;font-weight:600;color:#1F4E79;width:40%;}
        .hash-box{background:#f8faff;border:1px solid #e2e8f0;border-radius:6px;padding:12px;font-family:monospace;font-size:10px;word-break:break-all;color:#666;margin-bottom:20px;}
        .footer{text-align:center;color:#999;font-size:11px;margin-top:30px;border-top:1px solid #eee;padding-top:16px;}
        .seal{text-align:center;font-size:48px;margin:16px 0;}
        .valid{background:#d1fae5;color:#059669;padding:8px 16px;border-radius:99px;font-weight:700;display:inline-block;font-size:14px;margin-bottom:16px;}
      </style></head><body>
      <div class="header">
        <div class="logo">LS-AgriFlow</div>
        <div class="subtitle">Lesotho Agricultural Supply Chain Platform</div>
      </div>
      <div class="seal">📜</div>
      <h2 style="text-align:center">EXPORT CERTIFICATE</h2>
      <div style="text-align:center;margin-bottom:20px"><span class="valid">✓ BLOCKCHAIN VERIFIED</span></div>
      <table>
        <tr><td>Certificate ID</td><td>${cert.id}</td></tr>
        <tr><td>Issue Date</td><td>${new Date(cert.issuedAt).toLocaleString()}</td></tr>
        <tr><td>Issued By</td><td>${cert.issuedBy}</td></tr>
      </table>
      <h2>Batch Details</h2>
      <table>
        <tr><td>Batch ID</td><td>${batch.id}</td></tr>
        <tr><td>Product Type</td><td>${batch.productType}</td></tr>
        <tr><td>Weight</td><td>${batch.weight} kg</td></tr>
        <tr><td>Grade</td><td>${batch.grade}</td></tr>
        <tr><td>Origin Region</td><td>${batch.region}, Lesotho</td></tr>
        <tr><td>Harvest Date</td><td>${batch.harvestDate}</td></tr>
      </table>
      <h2>Parties</h2>
      <table>
        <tr><td>Farmer / Seller</td><td>${farmer?.name || order.sellerId}</td></tr>
        <tr><td>Buyer</td><td>${user.name} (${user.company || user.id})</td></tr>
        <tr><td>Order ID</td><td>${order.id}</td></tr>
        <tr><td>Transaction Value</td><td>LSL ${order.price.toLocaleString()}</td></tr>
      </table>
      <h2>Provenance Hash</h2>
      <div class="hash-box">SHA-256: ${cert.proofHash}</div>
      <div class="footer">
        This certificate was automatically generated by LS-AgriFlow (LSAgriFlow_Supply_v1) and records an immutable blockchain transaction.<br/>
        Verify this batch at: ls-agriflow.gov.ls/verify?batch=${batch.id}
      </div>
      </body></html>`)
    win.document.close()
    win.print()
  }

  return (
    <Layout title="My Orders">
      <div className="section-header">
        <div>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>My Orders</h2>
          <p className="text-muted">{orders.length} order{orders.length !== 1 ? 's' : ''} total</p>
        </div>
        <button className="btn btn-ghost btn-sm" onClick={() => navigate('/marketplace')}>← Back to Marketplace</button>
      </div>

      {orders.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <div className="empty-icon">🛒</div>
            <div className="empty-title">No orders yet</div>
            <div className="empty-desc">Browse the marketplace and purchase a verified batch</div>
            <button className="btn btn-primary btn-sm" onClick={() => navigate('/marketplace')}>Browse Marketplace</button>
          </div>
        </div>
      ) : (
        <div>
          {orders.map(o => {
            const e = enrich(o)
            return (
              <div key={o.id} className="card" style={{ marginBottom: 16 }}>
                <div className="card-header">
                  <div>
                    <span className="card-title">{e.batch?.productType} — {e.batch?.weight} kg</span>
                    <span className="text-muted text-sm" style={{ marginLeft: 10 }}>Order: {o.id}</span>
                  </div>
                  <Badge status={o.status === 'COMPLETED' ? 'CERTIFIED' : o.status} />
                </div>
                <div className="card-body">
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))', gap: 12, marginBottom: 14 }}>
                    {[
                      ['Product', e.batch?.productType],
                      ['Weight', `${e.batch?.weight} kg`],
                      ['Grade', e.batch?.grade],
                      ['Region', e.batch?.region],
                      ['Farmer', e.farmer?.name],
                      ['Price', `M${o.price?.toLocaleString()} LSL`],
                      ['Date', new Date(o.createdAt).toLocaleDateString()],
                      ['Certificate', e.cert?.id || 'Generating...'],
                    ].map(([k, v]) => (
                      <div key={k} style={{ background: 'var(--bg)', padding: '8px 10px', borderRadius: 'var(--radius-sm)' }}>
                        <div className="text-muted" style={{ fontSize: 11 }}>{k}</div>
                        <div style={{ fontWeight: 500, fontSize: 13 }}>{v}</div>
                      </div>
                    ))}
                  </div>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button className="btn btn-ghost btn-sm" onClick={() => setSelected(selected?.id === o.id ? null : o)}>
                      {selected?.id === o.id ? '▲ Hide' : '⛓ View Chain'}
                    </button>
                    {e.cert && (
                      <button className="btn btn-primary btn-sm" onClick={() => printCert(e.cert, o, e.batch, e.farmer)}>
                        📜 Print Export Certificate
                      </button>
                    )}
                  </div>
                  {selected?.id === o.id && (
                    <div style={{ marginTop: 16, borderTop: '1px solid var(--border)', paddingTop: 16 }}>
                      <ChainViewer transactions={e.txns} />
                    </div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </Layout>
  )
}
